package handler

const (
	CallbackBuy               = "buy"
	CallbackSell              = "sell"
	CallbackStart             = "start"
	CallbackConnect           = "connect"
	CallbackPayment           = "payment"
	CallbackTrial             = "trial"
	CallbackActivateTrial     = "activate_trial"
	CallbackReferral          = "referral"
	CallbackReferralList      = "referral_list"
	CallbackManageDevices     = "manage_devices"
	CallbackDevices           = "devices"
	CallbackDeleteDevice      = "delete_device_"
	CallbackAddDevice         = "add_device"
	CallbackAddDeviceConfirm  = "add_device_confirm"
	CallbackAddDeviceApply    = "add_device_apply"
	CallbackAddDevicePayment  = "add_device_payment"
	CallbackRenewExtraHwid    = "renew_extra_hwid"
	CallbackPurchaseHistory   = "purchase_history"
	CallbackBroadcastConfirm  = "broadcast_confirm"
	CallbackBroadcastCancel   = "broadcast_cancel"
	CallbackBroadcastAll      = "broadcast_all"
	CallbackBroadcastActive   = "broadcast_active"
	CallbackBroadcastInactive   = "broadcast_inactive"
	CallbackBroadcastBackAdmin  = "broadcast_back_admin"

	CallbackAdminPanel   = "admin_panel"
	CallbackAdminBroadcast = "admin_bc"
	CallbackAdminSync    = "admin_sync"
	CallbackAdminPromo   = "admin_promo"

	CallbackPromoRoot     = "promo_root"
	CallbackPromoList     = "promo_list"
	CallbackPromoNew      = "promo_new"
	CallbackPromoStatsAll = "promo_stats_all"
	CallbackPromoCard     = "promo_card"
	CallbackPromoNewType  = "promo_ntype"
	CallbackPromoDel      = "promo_del"
	CallbackPromoDelYes   = "promo_yes"
	CallbackPromoToggle   = "promo_toggle"
	CallbackPromoFirstPur = "promo_fp"
	CallbackPromoStat      = "promo_stat"
	CallbackPromoEdit          = "promo_edit"
	CallbackPromoEditValid     = "promo_ev"
	CallbackPromoEditMax       = "promo_em"
	CallbackPromoEditSubDays   = "promo_esd"
	CallbackPromoEditTrialDays = "promo_etd"
	CallbackEnterPromo         = "enter_promo"
)
