package handler

const (
	CallbackBuy = "buy"

	// BroadcastInlineQuery — суффикс callback у кнопок под постом рассылки: обработчики не трогают исходное сообщение, шлют новое.
	BroadcastInlineQuery = "?bc=1"
	CallbackSell              = "sell"
	CallbackStart             = "start"
	CallbackConnect           = "connect"
	CallbackPayment           = "payment"
	CallbackTrial             = "trial"
	CallbackActivateTrial     = "activate_trial"
	CallbackReferral          = "referral"
	CallbackReferralList      = "referral_list"
	CallbackManageDevices     = "manage_devices"
	CallbackDevices           = "devices"
	CallbackDeleteDevice      = "delete_device_"
	CallbackAddDevice         = "add_device"
	CallbackAddDeviceConfirm  = "add_device_confirm"
	CallbackAddDeviceApply    = "add_device_apply"
	CallbackAddDevicePayment  = "add_device_payment"
	CallbackRenewExtraHwid    = "renew_extra_hwid"
	CallbackPurchaseHistory   = "purchase_history"
	CallbackBroadcastConfirm  = "broadcast_confirm"
	CallbackBroadcastCancel   = "broadcast_cancel"
	CallbackBroadcastAll           = "broadcast_all"
	CallbackBroadcastActive        = "broadcast_active"
	CallbackBroadcastInactive      = "broadcast_inactive"
	CallbackBroadcastActivePaid    = "bc_aud_ap"
	CallbackBroadcastActiveTrial   = "bc_aud_at"
	CallbackBroadcastActiveAllSeg  = "bc_aud_aa"
	CallbackBroadcastInactivePaid  = "bc_aud_ip"
	CallbackBroadcastInactiveTrial = "bc_aud_it"
	CallbackBroadcastInactiveAllSeg = "bc_aud_ia"
	CallbackBroadcastBackAudience  = "bc_aud_b"
	CallbackBroadcastBackAdmin     = "broadcast_back_admin"
	CallbackBroadcastToggleMain = "bc_t_main"
	CallbackBroadcastTogglePromo = "bc_t_prm"
	CallbackBroadcastToggleVPN   = "bc_t_vpn"
	CallbackBroadcastToggleBuy   = "bc_t_buy"
	CallbackBroadcastButtonsNext = "bc_next"

	CallbackAdminPanel   = "admin_panel"
	CallbackAdminBroadcast = "admin_bc"
	CallbackAdminSync    = "admin_sync"
	CallbackAdminPromo   = "admin_promo"
	CallbackAdminTariffs = "admin_tariffs"

	CallbackAdminStatsRoot    = "as_r"
	CallbackAdminStatsUsers   = "as_u"
	CallbackAdminStatsSubs    = "as_s"
	CallbackAdminStatsRevenue = "as_v"
	CallbackAdminStatsRef     = "as_f"
	CallbackAdminStatsSummary = "as_m"

	CallbackAdminInfraRoot   = "ib_r"
	CallbackAdminInfraNodes  = "ib_n"
	CallbackAdminInfraNotify = "ib_u"
	CallbackAdminInfraHist   = "ib_h"
	CallbackAdminInfraProv   = "ib_p"
	CallbackAdminInfraToggle = "ibt"
	CallbackTariffNew    = "tf_new"
	// Префиксы callback: tf_v?, tf_t?, tf_d?, tf_y?, tf_s?, tf_q?, tf_sc?, tf_sa?, tf_nm?, tf_tt?, tf_td?, tf_tl?, tf_ep?, tf_ds?, tf_ca?, tf_wc?

	CallbackPromoRoot     = "promo_root"
	CallbackPromoList     = "promo_list"
	CallbackPromoNew      = "promo_new"
	CallbackPromoStatsAll = "promo_stats_all"
	CallbackPromoCard     = "promo_card"
	CallbackPromoNewType  = "promo_ntype"
	CallbackPromoDiscKind       = "promo_dk"
	CallbackPromoSubDaysScope   = "promo_sds"
	CallbackPromoDel      = "promo_del"
	CallbackPromoDelYes   = "promo_yes"
	CallbackPromoToggle   = "promo_toggle"
	CallbackPromoFirstPur = "promo_fp"
	CallbackPromoStat      = "promo_stat"
	CallbackPromoEdit          = "promo_edit"
	CallbackPromoEditValid     = "promo_ev"
	CallbackPromoEditMax       = "promo_em"
	CallbackPromoEditSubDays   = "promo_esd"
	CallbackPromoEditTrialDays = "promo_etd"
	CallbackPromoEditSubsTariff    = "promo_xts"
	CallbackPromoEditSubsTariffSet = "promo_xta"
	CallbackPromoEditDiscPay       = "promo_edp"
	CallbackEnterPromo         = "enter_promo"
)
