package handler

const (
	CallbackBuy               = "buy"
	CallbackSell              = "sell"
	CallbackStart             = "start"
	CallbackConnect           = "connect"
	CallbackPayment           = "payment"
	CallbackTrial             = "trial"
	CallbackActivateTrial     = "activate_trial"
	CallbackReferral          = "referral"
	CallbackReferralList      = "referral_list"
	CallbackManageDevices     = "manage_devices"
	CallbackDevices           = "devices"
	CallbackDeleteDevice      = "delete_device_"
	CallbackAddDevice         = "add_device"
	CallbackAddDeviceConfirm  = "add_device_confirm"
	CallbackAddDeviceApply    = "add_device_apply"
	CallbackAddDevicePayment  = "add_device_payment"
	CallbackRenewExtraHwid    = "renew_extra_hwid"
	CallbackPurchaseHistory   = "purchase_history"
	CallbackBroadcastConfirm  = "broadcast_confirm"
	CallbackBroadcastCancel   = "broadcast_cancel"
	CallbackBroadcastAll      = "broadcast_all"
	CallbackBroadcastActive   = "broadcast_active"
	CallbackBroadcastInactive = "broadcast_inactive"
)
